### ISSUE TITLE
typo in path

### ISSUE THREAD

**Issue by psolarcz** [CiscoTestAutomation/CL-DevNet-2595#1]
mock_device_cli --os nxos --mock_data_dir mocked_device/initial_yamls/nxos --state execute

instead of mocked_device - should be mocked_devices

**Comment by jeaubin** [comment]
Thanks!

I have actually fixed this last night; but did not push yet. 

I am still writing the Workshop,  I'll be adding a few more commit with new functionality.

as you go through it,  let me know if you see any improvement that could be done.
