### ISSUE TITLE
robot doesn't work

### ISSUE THREAD

**Issue by psolarcz** [CiscoTestAutomation/CL-DevNet-2595#2]
When I run robot it doesn't work:

(devnet-2595) XXX@ubuntu:~/devnet-2595/workshop/robot_initial_snapshot$ robot --outputdir run robot_initial_snapshot.robot
==============================================================================
Robot Initial Snapshot                                                        
==============================================================================
Connect                                                               | FAIL |
LoadError: Content of '../tb.yaml' failed to load into a dict.
Got: ../tb.yaml
------------------------------------------------------------------------------
Profile the devices                                                   | FAIL |
AttributeError: It is mandatory to 'use genie testbed ' command first.
------------------------------------------------------------------------------
Robot Initial Snapshot                                                | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
Output:  /home/XXX/devnet-2595/workshop/robot_initial_snapshot/run/output.xml
Log:     /home/XXX/devnet-2595/workshop/robot_initial_snapshot/run/log.html
Report:  /home/XXX/devnet-2595/workshop/robot_initial_snapshot/run/report.html

**Comment by jeaubin** [comment]
This is expected right now;

Part of the package to get this working will be released today on DevNet.

I'll let you know when its all executable.

**Comment by jeaubin** [comment]
@psolarcz  all has been released and the workshop is working as expected now.

Give it a try and let me know if you got any other comments!
